import { Artesanato } from '../../artesanato';

export const produtos: Artesanato[] = [
  {
    id: 1,
    nome: 'Vaso Decorativo Coração',
    preco: 79.9,
    descricao:
      'Vaso decorativo artesanal com suporte em formato de coração e acabamento marrom texturizado.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 30 cm de altura x 18 cm de largura',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso_coracao-1.jpeg',
      'produtos/vaso-coracao-2.jpeg',
      'produtos/vaso-coracao-3.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Marrom',
    acabamento: 'Texturizado',
    uso: ['Flores artificiais', 'Plantas pequenas', 'Decoração'],
    ambiente: ['Sala', 'Hall de entrada', 'Varanda coberta'],
  },

  {
    id: 2,
    nome: 'Vaso Decorativo Alto Texturizado',
    preco: 119.9,
    descricao:
      'Vaso decorativo artesanal de formato cilíndrico, com acabamento texturizado e pintura em tom amarelo mostarda. Ideal para compor a decoração de salas, halls, varandas e ambientes internos, podendo ser utilizado com flores artificiais, folhagens ou plantas ornamentais.',
    disponivel: true,
    quantidade: 4,
    dimensoes: 'Aproximadamente 60 cm de altura x 22 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso-texturizado-1.jpeg',
      'produtos/vaso-texturizado-2.jpeg',
      'produtos/vaso-texturizado-3.jpeg',
      'produtos/vaso-texturizado-4.jpeg',
      'produtos/vaso-texturizado-5.jpeg',
      'produtos/vaso-texturizado-6.jpeg',
      'produtos/vaso-texturizado-7.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Amarelo mostarda',
    acabamento: 'Texturizado fosco',
    uso: ['Flores artificiais', 'Folhagens', 'Plantas ornamentais'],
    ambiente: ['Sala', 'Varanda', 'Hall', 'Escritório'],
  },
  {
    id: 3,
    nome: 'Centro de Mesa Mãos Douradas',
    preco: 140.0,
    descricao:
      'Peça decorativa artesanal composta por uma base em formato de mãos sustentando um recipiente com acabamento texturizado. Ideal para decorar salas, halls de entrada, mesas de centro e aparadores.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 35 cm de altura x 30 cm de largura',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/recipiente-mao-2.jpeg',
      'produtos/recipiente-mao-1.jpeg',
      'produtos/recipiente-mao-3.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Dourado e branco',
    acabamento: 'Texturizado',
    uso: ['Centro de mesa', 'Fruteira decorativa', 'Arranjos'],
    ambiente: ['Sala', 'Hall', 'Aparador'],
  },
  {
    id: 4,
    nome: 'Vaso Decorativo Alto',
    preco: 120.0,
    descricao:
      'Vaso decorativo artesanal de formato arredondado com acabamento texturizado na cor preta. Acompanha prato de apoio e é ideal para o cultivo de plantas ornamentais ou composição de ambientes internos e externos cobertos.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 45 cm de altura x 30 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso-decorativo-1.jpeg',
      'produtos/vaso-decorativo-2.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Preto',
    acabamento: 'Texturizado',
    uso: ['Plantas ornamentais', 'Flores', 'Decoração'],
    ambiente: ['Área interna', 'Varanda coberta', 'Jardim'],
  },
  {
    id: 5,
    nome: 'Vaso Decorativo Taça Rústica',
    preco: 240.0,
    descricao:
      'Vaso decorativo artesanal em formato de taça, com base inspirada em tronco de árvore e acabamento texturizado em tom dourado. Ideal para compor a decoração de salas, halls de entrada, varandas e ambientes sofisticados, podendo ser utilizado com flores, arranjos artificiais ou plantas ornamentais.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 45 cm de altura x 35 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso-taca-rustica-1.jpeg',
      'produtos/vaso-taca-rustica-2.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Dourado',
    acabamento: 'Texturizado',
    uso: ['Arranjos', 'Flores artificiais', 'Decoração'],
    ambiente: ['Sala', 'Hall', 'Recepção'],
  },
  {
    id: 6,
    nome: 'Vaso Decorativo Borda Orgânica',
    preco: 120.0,
    descricao:
      'Vaso decorativo artesanal com bordas irregulares e acabamento texturizado em tom terracota. Seu design orgânico proporciona um visual rústico e elegante, sendo ideal para flores, folhagens, plantas ornamentais ou como peça decorativa em diversos ambientes.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 35 cm de altura x 30 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso-borda-organica-1.jpeg',
      'produtos/vaso-borda-organica-2.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Terracota',
    acabamento: 'Rústico texturizado',
    uso: ['Flores', 'Folhagens', 'Plantas ornamentais'],
    ambiente: ['Sala', 'Varanda', 'Jardim coberto'],
  },
  {
    id: 7,
    nome: 'Vaso Decorativo Clássico Mostarda',
    preco: 130.0,
    descricao:
      'Vaso decorativo artesanal de formato clássico com acabamento texturizado na cor mostarda. Acompanha prato de apoio e é ideal para plantas ornamentais, flores e composição de ambientes internos e externos cobertos.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 40 cm de altura x 30 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: ['produtos/vaso-mostarda-1.jpeg'],
    material: 'Cimento artesanal',
    cor: 'Mostarda',
    acabamento: 'Texturizado',
    uso: ['Plantas ornamentais', 'Flores', 'Decoração'],
    ambiente: ['Sala', 'Varanda', 'Jardim'],
  },
  {
    id: 8,
    nome: 'Vaso Decorativo Dourado Premium',
    preco: 150.0,
    descricao:
      'Vaso decorativo artesanal com acabamento dourado metálico e textura em relevo. Seu design elegante é ideal para valorizar a decoração de salas, halls, escritórios e varandas, podendo ser utilizado com plantas ornamentais ou flores artificiais.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 45 cm de altura x 28 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: ['produtos/vaso-dourado-1.jpeg'],
    material: 'Cimento artesanal',
    cor: 'Dourado metálico',
    acabamento: 'Metalizado texturizado',
    uso: ['Flores artificiais', 'Plantas ornamentais', 'Decoração'],
    ambiente: ['Sala', 'Escritório', 'Hall', 'Recepção'],
  },
  {
    id: 9,
    nome: 'Vaso Decorativo Geométrico Bege',
    preco: 110.0,
    descricao:
      'Vaso decorativo artesanal com acabamento texturizado em tom bege e detalhes geométricos em marrom. Acompanha prato de apoio e é ideal para plantas ornamentais, flores e composição de ambientes internos e externos cobertos.',
    disponivel: true,
    quantidade: 1,
    dimensoes: 'Aproximadamente 35 cm de altura x 28 cm de diâmetro',
    tempoProducao: 'Pronto para envio',
    fotos: [
      'produtos/vaso-geometrico-1.jpeg',
      'produtos/vaso-geometrico-2.jpeg',
      'produtos/vaso-geometrico-3.jpeg',
    ],
    material: 'Cimento artesanal',
    cor: 'Bege com detalhes marrons',
    acabamento: 'Texturizado',
    uso: ['Plantas ornamentais', 'Flores', 'Decoração'],
    ambiente: ['Sala', 'Varanda', 'Jardim coberto'],
  },
];
